from lib.templates.types import RequiredSectionDef, TemplateDefinition
from lib.templates.checks import (
    GENERIC_PLACEHOLDER_PATTERNS,
    transport_approval_email_check,
    testing_results_check,
)


def _sec(key, aliases, severity, min_words, why, question, placeholders=None, checks=None):
    return RequiredSectionDef(
        key=key,
        aliases=aliases,
        severity_if_missing=severity,
        min_word_count=min_words,
        why_it_matters=why,
        suggested_question=question,
        placeholder_patterns=placeholders or [],
        content_checks=checks or [],
    )


GENERIC_CORE: list[RequiredSectionDef] = [
    _sec(
        "purpose",
        ["purpose", "title", "overview", "introduction", "objective"],
        "Critical Missing",
        15,
        "Without a stated purpose, reviewers and developers cannot judge whether the design meets the actual business need.",
        "What business problem is this specification intended to solve, in one or two sentences?",
    ),
    _sec(
        "scope",
        ["scope", "in scope", "in-scope"],
        "Critical Missing",
        15,
        "An unclear scope leads to disagreements about what is included in the build and increases the risk of missed requirements.",
        "What specifically is included in this change? Can you list the concrete deliverables?",
    ),
    _sec(
        "out_of_scope",
        ["out of scope", "out-of-scope", "exclusions"],
        "Important Gap",
        8,
        "Without explicit exclusions, stakeholders may assume adjacent functionality is included, causing scope creep or missed expectations.",
        "What related functionality is explicitly NOT covered by this specification?",
    ),
    _sec(
        "business_context",
        ["business context", "background", "business justification"],
        "Important Gap",
        20,
        "Missing business context makes it hard to evaluate trade-offs or prioritize this work against other initiatives.",
        "What business process or driver led to this requirement?",
    ),
    _sec(
        "process_flow",
        ["process flow", "process description", "workflow", "as-is / to-be", "as is to be"],
        "Important Gap",
        25,
        "Without a described process flow, developers must guess at sequencing and system behavior, increasing rework risk.",
        "Can you walk through the end-to-end process flow, step by step, including who or what triggers each step?",
    ),
    _sec(
        "inputs_outputs",
        ["inputs and outputs", "inputs/outputs", "input output", "data inputs"],
        "Critical Missing",
        15,
        "Undefined inputs/outputs are one of the most common causes of build rework and integration mismatches.",
        "What are the exact input fields/sources and expected output fields/destinations, including data types?",
    ),
    _sec(
        "validations",
        ["validations", "validation rules", "business rules"],
        "Important Gap",
        15,
        "Missing validation rules leave data quality and business rule enforcement to developer interpretation.",
        "What validation rules must be enforced, and what should happen when a validation fails?",
    ),
    _sec(
        "exception_handling",
        ["exception handling", "error handling", "error scenarios"],
        "Important Gap",
        15,
        "Without defined exception handling, production incidents are more likely and harder to triage.",
        "How should the system behave when an error, timeout, or invalid state occurs?",
    ),
    _sec(
        "integration_interfaces",
        ["integration", "interfaces", "interface details", "integration/interface details"],
        "Important Gap",
        15,
        "Undocumented integrations create hidden dependencies that surface late as production defects.",
        "Which upstream/downstream systems or interfaces does this change touch, and how?",
    ),
    _sec(
        "dependencies_assumptions",
        ["dependencies", "assumptions", "dependencies and assumptions"],
        "Important Gap",
        10,
        "Unstated assumptions often turn out to be wrong, causing late-stage scope or design changes.",
        "What assumptions is this design based on, and what other work does it depend on?",
    ),
    _sec(
        "security_authorization",
        ["security", "authorization", "security/authorization impact", "access control"],
        "Important Gap",
        8,
        "Security and authorization gaps discovered late are expensive to fix and can block go-live.",
        "Does this change introduce new access, roles, or data exposure that needs authorization review?",
    ),
    _sec(
        "batch_job_impact",
        ["batch impact", "job impact", "batch/job impact", "background job"],
        "Improvement Suggestion",
        8,
        "Unplanned batch/job impact can affect nightly processing windows and downstream schedules.",
        "Does this change affect any batch jobs, schedules, or background processing?",
    ),
    _sec(
        "reporting_impact",
        ["reporting impact", "reporting", "report changes"],
        "Improvement Suggestion",
        8,
        "Unaddressed reporting impact can leave stakeholders with stale or incorrect reports after go-live.",
        "Does this change affect any existing reports, dashboards, or extracts?",
    ),
    _sec(
        "acceptance_criteria",
        ["acceptance criteria", "testability", "test scenarios", "acceptance criteria or testability"],
        "Critical Missing",
        15,
        "Without testable acceptance criteria, QA and UAT cannot objectively confirm the requirement was met.",
        "What specific, testable conditions must be true for this requirement to be considered done?",
    ),
]

GENERIC_TEMPLATE = TemplateDefinition(
    id="generic-fs",
    name="Generic Functional Specification",
    description="General-purpose functional specification review, applicable to any project.",
    required_sections=list(GENERIC_CORE),
)

SAP_FS_TEMPLATE = TemplateDefinition(
    id="sap-fs",
    name="SAP Functional Specification",
    description="Functional specification review with SAP-specific checks (transactions, objects, authorizations, jobs).",
    required_sections=list(GENERIC_CORE)
    + [
        _sec(
            "sap_transaction_codes",
            ["transaction codes", "impacted transaction codes", "t-codes", "tcodes"],
            "Improvement Suggestion",
            5,
            "Undocumented transaction code impact makes it harder to scope testing and authorization changes.",
            "Which SAP transaction codes are impacted or newly introduced by this change?",
        ),
        _sec(
            "sap_business_objects",
            ["business objects", "impacted business objects"],
            "Improvement Suggestion",
            5,
            "Business object impact is needed to assess downstream effects on related processes.",
            "Which SAP business objects (e.g., Sales Order, Material, Vendor) does this affect?",
        ),
        _sec(
            "sap_data_objects",
            ["table", "structure", "api", "idoc", "table / structure / api / idoc references", "data objects"],
            "Important Gap",
            8,
            "Missing table/structure/API/IDoc references force developers to reverse-engineer the data model.",
            "Which tables, structures, APIs, or IDocs are read from or written to?",
        ),
        _sec(
            "sap_posting_logic",
            ["posting logic"],
            "Important Gap",
            10,
            "Undefined posting logic risks incorrect financial or material postings in production.",
            "What is the exact posting logic, including document types and posting keys where relevant?",
        ),
        _sec(
            "sap_error_reprocessing",
            ["error handling and reprocessing", "reprocessing"],
            "Important Gap",
            10,
            "Without a reprocessing strategy, failed postings/interfaces can silently pile up unresolved.",
            "How are failed transactions identified, logged, and reprocessed?",
        ),
        _sec(
            "sap_job_scheduling",
            ["job scheduling", "background impact", "job scheduling / background impact"],
            "Improvement Suggestion",
            5,
            "Job scheduling changes can conflict with existing batch windows if not documented.",
            "Does this require a new background job or changes to an existing job's schedule?",
        ),
        _sec(
            "sap_authorization_objects",
            ["authorization object impact", "authorization objects"],
            "Important Gap",
            5,
            "Authorization object gaps are a common cause of late security review findings.",
            "Are new or existing authorization objects impacted by this change?",
        ),
        _sec(
            "sap_reconciliation_audit",
            ["reconciliation", "audit impact", "reconciliation / audit impact"],
            "Improvement Suggestion",
            5,
            "Missing reconciliation/audit considerations can create compliance gaps post go-live.",
            "How will reconciliation and audit trail be maintained for this change?",
        ),
    ],
)

SAP_INTEGRATION_TEMPLATE = TemplateDefinition(
    id="sap-integration",
    name="SAP Integration / Interface Specification",
    description="Review focused on interface design: systems, mapping, error handling, monitoring.",
    required_sections=[
        _sec(
            "interface_overview",
            ["overview", "interface overview", "purpose"],
            "Critical Missing",
            15,
            "Without an overview, reviewers cannot understand the purpose of the interface.",
            "What is the purpose of this interface and which business process does it support?",
        ),
        _sec(
            "source_target_systems",
            ["source system", "target system", "source and target systems"],
            "Critical Missing",
            8,
            "Undefined source/target systems make integration testing and environment setup impossible to plan.",
            "What are the exact source and target systems, including environment/instance details?",
        ),
        _sec(
            "interface_method",
            ["interface method", "idoc", "api", "file", "integration method"],
            "Critical Missing",
            8,
            "The integration method (IDoc, API, file, etc.) drives technical design and error handling patterns.",
            "What integration method/technology is used (IDoc, REST/SOAP API, file transfer, etc.)?",
        ),
        _sec(
            "data_mapping",
            ["data mapping", "field mapping"],
            "Critical Missing",
            15,
            "Missing field-level mapping is one of the top causes of interface defects.",
            "What is the field-level mapping between source and target, including transformations?",
        ),
        _sec(
            "frequency_scheduling",
            ["frequency", "scheduling", "frequency/scheduling"],
            "Important Gap",
            5,
            "Undefined frequency affects downstream data freshness and job scheduling conflicts.",
            "How frequently does this interface run, and is it real-time, batch, or triggered?",
        ),
        _sec(
            "error_handling_reprocessing",
            ["error handling", "reprocessing", "error handling and reprocessing"],
            "Critical Missing",
            15,
            "Interfaces without clear error handling routinely cause silent data loss in production.",
            "How are interface failures detected, logged, alerted on, and reprocessed?",
        ),
        _sec(
            "volume_performance",
            ["volume", "performance", "volume/performance"],
            "Improvement Suggestion",
            5,
            "Undefined volume expectations can lead to performance issues discovered only in production.",
            "What is the expected data volume and performance/SLA requirement for this interface?",
        ),
        _sec(
            "security_interface",
            ["security", "authentication", "encryption"],
            "Important Gap",
            5,
            "Interface security gaps are a common audit finding if not addressed at design time.",
            "How is the interface authenticated and secured (e.g., certificates, encryption in transit)?",
        ),
        _sec(
            "monitoring_alerting",
            ["monitoring", "alerting", "monitoring/alerting"],
            "Improvement Suggestion",
            5,
            "Without monitoring, interface failures may go unnoticed until a business impact is reported.",
            "How will this interface be monitored, and who is alerted on failure?",
        ),
        _sec(
            "testing_acceptance",
            ["testing", "acceptance criteria", "test scenarios"],
            "Critical Missing",
            10,
            "Without testable acceptance criteria, interface testing cannot objectively confirm correctness.",
            "What specific test scenarios must pass for this interface to be considered ready for go-live?",
        ),
    ],
)

COMPANY_SOLUTION_DESIGN_TEMPLATE = TemplateDefinition(
    id="company-solution-design",
    name="Company FS Template (Solution Design Document)",
    description="Matches the company's Solution Design Document FS template, including transport approval and testing-results checks.",
    disallow_extra_sections=True,
    required_sections=[
        _sec(
            "fs_summary",
            ["functional specification summary"],
            "Critical Missing",
            20,
            "Without a clear summary, reviewers cannot quickly judge the context, problem, and proposed solution before reading the full document.",
            "Can you write a single-paragraph summary covering the context, the problem, and the proposed solution?",
            placeholders=GENERIC_PLACEHOLDER_PATTERNS,
        ),
        _sec(
            "transport_request_approval",
            ["transport request approval"],
            "Critical Missing",
            5,
            "A transport request moved without documented approval cannot be audited and may violate change-control policy.",
            "Who approved this transport request, and can the approval email or written confirmation be attached here?",
            checks=[transport_approval_email_check],
        ),
        _sec(
            "background_context",
            ["background and context"],
            "Important Gap",
            20,
            "Without background and context, reviewers cannot judge whether the proposed solution actually fits the underlying business situation.",
            "What is the business background and context driving this change?",
            placeholders=GENERIC_PLACEHOLDER_PATTERNS,
        ),
        _sec(
            "requirements",
            ["requirements"],
            "Critical Missing",
            25,
            "Undefined requirements are the most common cause of rework and scope disputes during build.",
            "Can you break down the specific functional requirements this change must deliver?",
            placeholders=GENERIC_PLACEHOLDER_PATTERNS,
        ),
        _sec(
            "dependencies_constraints",
            ["dependencies / constraints", "dependencies/constraints", "dependencies", "constraints"],
            "Important Gap",
            10,
            "Unstated dependencies and constraints often surface late as blockers during build or testing.",
            "What internal/external dependencies or constraints (schedule, access, data) affect this build?",
            placeholders=GENERIC_PLACEHOLDER_PATTERNS,
        ),
        _sec(
            "security_authorization",
            [
                "security, authorization, integrity, and controls",
                "security authorization integrity and controls",
                "security",
            ],
            "Critical Missing",
            10,
            "Security and authorization gaps found after go-live are expensive to fix and can trigger audit findings.",
            "What security, authorization, or data integrity considerations apply to this change, and who owns them?",
            placeholders=GENERIC_PLACEHOLDER_PATTERNS,
        ),
        _sec(
            "technical_specification",
            ["technical specification / solution", "technical specification/solution", "technical specification"],
            "Important Gap",
            15,
            "Without real technical detail, developers cannot estimate or build the solution without going back to the author.",
            "Can you add the architecture, data flow, configuration, and error-handling detail for this solution?",
            placeholders=GENERIC_PLACEHOLDER_PATTERNS,
        ),
        _sec(
            "test_results",
            ["test results", "testing", "unit testing evidence"],
            "Critical Missing",
            10,
            "Without recorded test results, the manager cannot confirm the change was actually validated before go-live.",
            "Can you attach the executed test cases with expected/actual output and pass/fail status?",
            placeholders=GENERIC_PLACEHOLDER_PATTERNS,
            checks=[testing_results_check],
        ),
    ],
)

TEMPLATES: list[TemplateDefinition] = [
    GENERIC_TEMPLATE,
    SAP_FS_TEMPLATE,
    SAP_INTEGRATION_TEMPLATE,
    COMPANY_SOLUTION_DESIGN_TEMPLATE,
]


def get_template_by_id(template_id: str) -> TemplateDefinition:
    for t in TEMPLATES:
        if t.id == template_id:
            return t
    raise ValueError(f"Unknown template id: {template_id}")
